### PR TITLE
Fix typo in README.md

### PR DESCRIPTION
**Pull request by SIMULATAN**
exising -> existing

### CODE REVIEW

**Comment by clayburn** [comment]
Thanks for the contribution @SIMULATAN! There are a couple of issues preventing a merge here. This repository requires 
- Commits to be signed before merging into `main`. See https://docs.github.com/articles/about-gpg/
- Commits to be signed-off for DCO: https://github.com/gradle/gradle-build-action/pull/351/checks?check_run_id=7111499986

**Comment by SIMULATAN** [comment]
Alright, I'll fix that soon.

**Comment by SIMULATAN** [comment]
@clayburn finally managed to get git to work properly, I think it should be fixed now.

**Comment by clayburn** [comment]
Thanks!

**Pull request merged**
