### PR TITLE
[Bugfix] Do not override content of gradle.properties if it is exist

### PR DESCRIPTION
**Pull request by mdolinin**
Prevent override existing properties that user set in `gradle.properties` file inside Gradle User Home

### CODE REVIEW

**Comment by bigdaz** [comment]
Thanks for the contribution. The intention was for the `gradle-build-action` to only restore Gradle User Home if it doesn't already exist. Unfortunately this is currently not the case: see #138 .

How is your workflow initializing `~/.gradle/gradle.properties` such that the `gradle-build-action` is overriding the content?

**Comment by mdolinin** [comment]
> Thanks for the contribution. The intention was for the `gradle-build-action` to only restore Gradle User Home if it doesn't already exist. Unfortunately this is currently not the case: see #138 .
> 
> How is your workflow initializing `~/.gradle/gradle.properties` such that the `gradle-build-action` is overriding the content?

We have separate step that creates and populate that file from external source. And if we execute that step before `gradle-build-action` content of the file will be replaced with one line  `org.gradle.daemon=false`. 
Current workaround is to execute init script after gradle build action:
```yaml
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        # Setup gradle should run before init script because it removes content from $GRADLE_USER_HOME/gradle.properties
      - name: Run init script
        run: |
          bash .github/scripts/init_env_workflows.sh
      - name: Execute Gradle Task
        run: ./gradlew build
```

**Comment by bigdaz** [comment]
Thanks again for the PR. I ended up adding a simpler fix that should still avoid overwriting an existing `gradle.properties` file: 702bb97ecb0ad7a8492a6f0fdbff0be3308a754e

**Comment by mdolinin** [comment]
@bigdaz Thanks for update

**Pull request closed without merging**
